### ISSUE TITLE
nest-electron 关于 preload 的返回值的疑问

### ISSUE THREAD

**Issue by edwinhuish** [Doubleshotjs/doubleshot#293]
有幸拜读了一下你的源码。有一个疑问，既然 main 返回的已经是一个 Promise， 为何还需要将返回的数据封装成  { data, error } 呢？ 直接按照 Promise 的方式返回并在接收的时候 catch 不是很好嘛？

**Comment by ArcherGu** [comment]
这个怎么说呢，其实只是个人习惯问题。因为我写前端时最常用axios，它的Response就是包含了data/error，所以我这里也返回data/error，在从c/s迁移到b/s时增加一些统一性。当然这个东西可能不太符合标准性用法，回头还是可以调整的。

这里没有绝对的对错或者特别的好处，仅仅是个人行为罢了😂

**Comment by edwinhuish** [comment]
谢谢大佬解惑。 回头提个PR。

另外，请教一下，如何在renderer处做一个统一的错误处理，并用element-plus弹出错误提示呢？

试过很多方法，暂时是通过这样实现的：

```javascript
// preload/index.ts

import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electron', {
  invoke: (channel: string, ...args: any[]) => ipcRenderer.invoke(channel, ...args)
});
```

```javascript
// render/api/electron.ts

import { ElMessage } from 'element-plus';

export async function invoke(channel: string, ...args: any[]) {
  const { data, error } = await window.electron.invoke(channel, ...args);

  if (error) {
    ElMessage.error(error.message);
    throw error;
  }

  return data;
}
```

然后 renderer 再调用 ``` invoke ``` 进行封装对应的接口函数。

但感觉这样有点 dirty， 有没有可以将接口函数写在 preload 里的方式呢？

**Comment by ArcherGu** [comment]
一般我们都是直接将channel在preload层封装好，暴露给renderer。你这样在preload等于直接暴露了一个最高级的`invoke`给renderer，可能会有安全问题。

至于你说的封装问题，这个都是仁者见仁智者见智，只要能解决问题，不必去刻意追求所谓的最佳实践。你在preload中写接口的时候，顺便把报错相关的逻辑也写了，也是可以的。

**Comment by edwinhuish** [comment]
第一次用electron，很懂东西不太清楚。想不到暴露最高级别的 ``` invoke ```  有什么弊端，因为毕竟 main 没有对应的函数的话，renderer 发起 invoke 也没用。如果有的话，和经过 preload 转一道貌似也没有什么区别。。。

**Comment by ArcherGu** [comment]
> 第一次用electron，很懂东西不太清楚。想不到暴露最高级别的 `invoke` 有什么弊端，因为毕竟 main 没有对应的函数的话，renderer 发起 invoke 也没用。如果有的话，和经过 preload 转一道貌似也没有什么区别。。。

你可以看一下文档中的建议: [安全事项](https://www.electronjs.org/zh/docs/latest/tutorial/context-isolation#%E5%AE%89%E5%85%A8%E4%BA%8B%E9%A1%B9)

**Comment by edwinhuish** [comment]
安全事项看过，所以我各种百度、Google、ChatGPT，都没有找到一个合适的，在 ```preload.ts``` 里做总的异常处理拦截的方式。所以才请假一下你。

我平时也是用 ``` axios ```， 一般都会用它的 ``` interceptors.response ``` 去对后端的 ``` response ``` 和 ``` exception ``` 做一个总的处理，这样就不需要每个 api 请求都catch一遍，仅需要对个别特殊的 api 请求做处理即可。

**Comment by ArcherGu** [comment]
你可以在 preload 里写一个总的拦截器，然后对 `contextBridge.exposeInMainWorld` 中暴露到 renderer 的方法进行一个统一的封装，这样你就有一个总的处理了。

**Comment by edwinhuish** [comment]
> 你可以在 preload 里写一个总的拦截器，然后对 `contextBridge.exposeInMainWorld` 中暴露到 renderer 的方法进行一个统一的封装，这样你就有一个总的处理了。

关键是如果是一个多窗口应用怎么办？怎么判断应该传递到那个窗口？

**Comment by ArcherGu** [comment]
1. 你可以将不同的 preload 加载到不同的窗口，做不同的处理。
2. 你可以在参数传入 preload 时增加一个窗口的 id，这部分你可以在前端的接口文件中做统一处理，然后根据窗口的 id 做不同处理。
3. 其他的办法，你可以网上找找。

**Comment by edwinhuish** [comment]
> 1. 你可以将不同的 preload 加载到不同的窗口，做不同的处理。
> 2. 你可以在参数传入 preload 时增加一个窗口的 id，这部分你可以在前端的接口文件中做统一处理，然后根据窗口的 id 做不同处理。
> 3. 其他的办法，你可以网上找找。

第一点麻烦能展开说一下吗？因为这里的 preload 注入用的是你的``` vite-plugin-doubleshot ```， 好像里面没有针对多窗口的方式？

暂时我的应用不涉及多窗口，只是在找最优解，避免为后期埋坑。

**Comment by ArcherGu** [comment]
首先在`vite-plugin-doubleshot`中, preload 配置的 `entry` 选项支持 `string | string[]`, 所以你可以同时转移好几份 preload 文件。
其次是多窗口创建，有两种方法：
1. 你可以用 `ElectronModule.registerAsync` 来创建一个窗口，同样的，你可以在 nestjs module 的 imports 中使用多个 `ElectronModule.registerAsync` 来创建多个窗口，不同的窗口的 `webPreferences.preload` 来加载不同的 preload。
2. 你也可以像常规的 electron 应用那样，通过renderer发送指令给main，或者main在特定条件下，使用 `BrowserWindow` 动态创建窗口，不同的窗口的 `webPreferences.preload` 来加载不同的 preload。

总体而言，反正就是用 `BrowserWindow` 来创建窗口，然后配置不同的窗口，这些和我的工具库无关，都是 electron 的部分。

**Comment by edwinhuish** [comment]
thx

**Comment by ArcherGu** [comment]
另外纠正一点，`vite-plugin-doubleshot` 只是一个 vite 生态下的插件，负责在 vite 模式下转译一些 electron 相关的 typescript 文件，顺便在 vite 启动后启动下 electron，它不涉及到诸如 preload 注入之类的 electron 运行时的操作。

**Comment by edwinhuish** [comment]
> 另外纠正一点，`vite-plugin-doubleshot` 只是一个 vite 生态下的插件，负责在 vite 模式下转译一些 electron 相关的 typescript 文件，顺便在 vite 启动后启动下 electron，它不涉及到诸如 preload 注入之类的 electron 运行时的操作。

主要是初次使用electron，对很多 api 和概念理解不深。谢谢你的解答。

**Comment by ArcherGu** [comment]
不客气，有什么问题可以随时交流，不过先建议查阅 electron 的文档。
