### ISSUE TITLE
请教为何要区分 IpcHandle 和 IpcOn?

### ISSUE THREAD

**Issue by edwinhuish** [Doubleshotjs/doubleshot#296]
看了一下文档： [进程间通信](https://www.electronjs.org/zh/docs/latest/tutorial/ipc)

新版的双向通讯```invoke```是在 electron 7 之后添加的，electron 的进程通讯有单向通讯和双向通讯。但是作为封装后的装饰器， 区分 ```IpcHandle``` （双向）和 ```IpcOn``` （单向）的作用/意义是什么呢？

貌似可以通过 ```invoke``` 返回 ``` void ``` 来达到无返回值的效果吧？

还是说单向通讯在electron内部的流程更简洁？速度更快？

**Comment by ArcherGu** [comment]
是的，其实 invoke/handle 可以完全替代 send/on，提供两个不同的装饰器，也只是为了符合当下 electron 的设计标准。因为在老项目进行改造时，可能同时存在 invoke 和 send，那最好也提供 handle 和 on 来做对应。
