### ISSUE TITLE
main 如何添加多个 entry

### ISSUE THREAD

**Issue by edwinhuish** [Doubleshotjs/doubleshot#305]
由于需要在electron里加入playwright，而 playwright启动的时候，需要另外一个入口文件。

但是看过你的 ``` VitePluginDoubleshot ```  的源码，好像写死了固定一个 ``` main ```, 固定一个 ``` preload``` (preload可以多入口）

请问有什么简单的方式可以让 ```main```  编译其他 ts 文件到 dist 吗？

**Comment by ArcherGu** [comment]
`main` 不会固定死的，请仔细看 typescript 给你的配置类型提示和介绍描述。
`VitePluginDoubleshot` 配置中：
-  `main`，表示 electron 启动时的文件
- `entry`，表示你的 typescript 的入口文件
- `outDir`，表示你的 `entry` 对应的文件转译后的输出目录，转译后输出的文件名称和 `entry` 对应的文件名称相同，只是类型为 `js`

**Comment by edwinhuish** [comment]
> `main` 不会固定死的，请仔细看 typescript 给你的配置类型提示和介绍描述。 `VitePluginDoubleshot` 配置中：
> 
> * `main`，表示 electron 启动时的文件
> * `entry`，表示你的 typescript 的入口文件
> * `outDir`，表示你的 `entry` 对应的文件转译后的输出目录，转译后输出的文件名称和 `entry` 对应的文件名称相同，只是类型为 `js`

你可能理解错了我的意思。也可能是我描述太累赘。

我是想问，如何在build的时候，编译另外一个不经过 main/index.ts 入口的 ts 文件到 main

**Comment by edwinhuish** [comment]
你可以理解为 main 里有多个入口文件

**Comment by ArcherGu** [comment]
`VitePluginDoubleshot ` 是一个专门针对 electron（也兼容普通的node项目） 的插件，electron 启动时只有一个入口，所以它也只提供一个入口。它不是一个专门的类似于 webpack/esbuild 那样的转译工具。

如果你想转译额外的 ts 文件，就使用别的工具进行转译。
