### ISSUE TITLE
属性名建议

### ISSUE THREAD

**Issue by edwinhuish** [Doubleshotjs/doubleshot#329]
下面的属性名`ipcEvt`改为 `event` 会更符合上下文，用户使用起来也更清晰。

另外，最好定义一个 interface/type 并 export，以便在使用时可以指定 context 类型。

https://github.com/Doubleshotjs/doubleshot/blob/ff46a5c4d8eacb07e09820513915ace0ec2d65df/packages/nest-electron/src/electron.transport.ts#L37-L39

**Comment by ArcherGu** [comment]
第一点就不改了，ipcEvt作为key也能辨识。

第二个下次release可以加上去，目前就自己写个解构类型吧。
