### ISSUE TITLE
存在消息多次传递

### ISSUE THREAD

**Issue by edwinhuish** [Doubleshotjs/doubleshot#330]
现在的逻辑是 `ipcMain` 拿到数据后，再次发起 nest 的消息事件，存在多余的消息处理。

另外 `MethodDecorator` 内使用了 `electron` 的生命周期`app.on('ready')`，存在隐患。

稍后将提一个 PR，改动有点大，你可以酌情关闭后重新用你的方式提交commit

**Comment by ArcherGu** [comment]
已经合并了👍。改动大小没有关系，只要是单一改动点就行了。
