### ISSUE TITLE
使用fork多进程，在打包时丢失文件

### ISSUE THREAD

**Issue by feiyu1995** [Doubleshotjs/doubleshot#529]

**Comment by ArcherGu** [comment]
我这边只会对主进程进行构建。所以你要手动去处理这些需要 fork 执行的进程文件，然后在最终打包时放入最后的 dist 目录中。这个库里是依赖 tsup，你可以利用 tsup来对这些代码进行打包构建，当然，你也可以用自己喜欢的构建工具来进行。
