### ISSUE TITLE
DSR using invalid kill signal

### ISSUE THREAD

**Issue by Superoryco** [Doubleshotjs/doubleshot#53]
[This](https://github.com/Doubleshotjs/doubleshot/blob/5f7f604cf9c895840bc7b13aa5c9b41524da8dba/packages/runner/src/run.ts#L73) should be `c.kill(9)` I think, currently, a failed nestjs build will throw ERR_UNKNOWN_SIGNAL in DSR.

also, will doubleshot supports multiple preload entry points?

Great project by the way!

**Comment by ArcherGu** [comment]
Thank you very much for your issue, I will try it! 😊

Multiple preload entry points are not supported, I changed it to a single entry when designing the configuration.
Does electron need multiple preload entries?

**Comment by ArcherGu** [comment]
@Superoryco I can't reproduce your error, can you describe it in more detail? `c.kill('0')` -> `c.kill(9)`

**Comment by Superoryco** [comment]
Sorry for late reply, actually, this can be reproduced in [template-vue-nest](https://github.com/Doubleshotjs/template-vue-nest), run the project and hit cmd+q to quit, following will be printed in terminal:
![Screen Shot 2022-09-28 at 11 50 58](https://user-images.githubusercontent.com/5689032/192683554-e1fc8b99-0a11-47f9-9927-6ea694f310f3.png)

**Comment by ArcherGu** [comment]
Sorry for late fix, now I had fixed [it].(https://github.com/Doubleshotjs/doubleshot/commit/6696df9da57ba3ee6f83e24d6d62af0a3596ec62)
